name = "Spaced Web Theme"
license = "MIT"
licenselink = "https://github.com/Morgscode/hugo-theme-spaced-web/blob/master/LICENSE"
description = "The Spaced Portfolio website Theme."
homepage = "https://spaced-web.xyz"
tags = ["Minimalistic", "Dark mode", "Blog", "Responsive", "Dark", "Light", "Portfolio", "Personal"]
features = ['']
min_version = "0.41.0"

[author]
  name = "Spaced Web"
  homepage = "https://spaced-web.xyz"
