name = "Spaced Digital Theme"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "The theme for Spaced Digital company website"
homepage = "https://spaced-digital.com"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Spaced Digital"
  homepage = "https://spaced-digital.com"
